# Generated by Django 4.1.5 on 2023-02-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionSet',
            new_name='QuizSet',
        ),
        migrations.RenameField(
            model_name='quizset',
            old_name='question_text',
            new_name='qtext',
        ),
    ]
