# Generated by Django 4.1.5 on 2023-02-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_questionset_quizset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizset',
            name='qtext',
            field=models.JSONField(),
        ),
    ]
