# Generated by Django 4.1.5 on 2023-02-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_quizset_qtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSet2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtext', models.TextField()),
            ],
        ),
    ]
