# Generated by Django 4.1.5 on 2023-02-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quizset2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizSet2',
            new_name='QuizSetText',
        ),
    ]
