# Generated by Django 4.1.5 on 2023-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_quizset2_quizsettext'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSetTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtext', models.CharField(max_length=255)),
                ('choices', models.CharField(max_length=255)),
                ('correct', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='QuizSetText',
        ),
    ]
