# Generated by Django 4.1.5 on 2023-02-08 13:43

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_quizsettest_delete_quizsettext'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSetText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='quizset',
            name='qtext',
            field=models.JSONField(encoder=json.encoder.JSONEncoder),
        ),
    ]
