# Generated by Django 4.1.5 on 2023-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quizsettext_alter_quizset_qtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizset',
            name='na',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizset',
            name='nq',
            field=models.IntegerField(default=0),
        ),
    ]
