# Generated by Django 4.1.5 on 2023-02-11 00:32

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_quizset_na_quizset_nq'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizset',
            name='subject',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='qtext',
            field=models.JSONField(default=dict, encoder=json.encoder.JSONEncoder),
        ),
    ]
