# Generated by Django 4.1.6 on 2023-02-13 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_quizset_subject_alter_quizset_qtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizSetTest',
        ),
        migrations.DeleteModel(
            name='QuizSetText',
        ),
        migrations.AddField(
            model_name='quizset',
            name='byplayer',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator('[+-/%<>&]', inverse_match=True)]),
        ),
        migrations.AddField(
            model_name='quizset',
            name='highscore',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quizset',
            name='timer',
            field=models.IntegerField(default=10),
        ),
    ]
