# Generated by Django 4.1.6 on 2023-02-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_quizsettest_delete_quizsettext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizset',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
