# Generated by Django 4.1.6 on 2023-02-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_quizset_highscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizset',
            name='highscore',
        ),
    ]
