# Generated by Django 4.1.6 on 2023-02-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_quizset_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizset',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
