# Generated by Django 4.1.7 on 2023-03-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_quizset_created_quizset_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizset',
            name='created',
            field=models.DateTimeField(blank=True, default='01-01-0000'),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='updated',
            field=models.DateTimeField(blank=True, default='01-01-0000'),
        ),
    ]
