# Generated by Django 4.1.7 on 2023-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_quizset_created_alter_quizset_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizset',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
