# Generated by Django 4.1.7 on 2023-03-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_quiz_alter_quizset_byplayer_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
