# Generated by Django 4.1.7 on 2023-03-15 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_quizset_rename_byplayer_quiz_by_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='qestions_form',
            new_name='questions_form',
        ),
    ]
