# Generated by Django 4.1.7 on 2023-03-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_quiz_temperature_alter_quiz_highscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='temperature',
            new_name='temper',
        ),
    ]
