# Generated by Django 4.1.7 on 2023-03-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_temperature_quiz_temper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='errors',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answers_mode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answers_sublists_equal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='corrects_valid_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
