# Generated by Django 4.1.7 on 2023-03-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_quiz_errors_quiz_answers_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='by_player',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
