# Generated by Django 4.1.7 on 2023-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_subject_quiz_topic_quiz_all_ok_quiz_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='response_text',
            field=models.CharField(default='', max_length=260),
        ),
    ]
