# Generated by Django 4.1.7 on 2023-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_quiz_response_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='response_text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
