# Generated by Django 4.1.7 on 2023-03-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_quiz_finish_reason_alter_quiz_response_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='highscore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
