# Generated by Django 4.1.7 on 2023-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_quiz_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='highscore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
