# Generated by Django 4.1.7 on 2023-03-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_quiz_highscore_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='highscore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
