# Generated by Django 4.1.7 on 2023-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_quiz_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='by_player',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
