# Generated by Django 4.1.7 on 2023-03-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_quiz_by_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='between_updates',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
