# Generated by Django 4.1.7 on 2023-03-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_betweenallupdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betweenallupdates',
            old_name='between_last_update',
            new_name='between_last_updates',
        ),
    ]
