# Generated by Django 4.1.7 on 2023-03-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_between_last_update_betweenallupdates_between_last_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='betweenallupdates',
            name='by_player_updated',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='betweenallupdates',
            name='highscore_percent_updated',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
