# Generated by Django 4.1.7 on 2023-03-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_betweenallupdates_by_player_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='views_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
