# Generated by Django 4.1.7 on 2023-03-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_quiz_views_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='between_updates',
            new_name='last_update',
        ),
    ]
