# Generated by Django 4.1.7 on 2023-03-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_rename_between_updates_quiz_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betweenallupdates',
            old_name='between_last_updates',
            new_name='between_updates',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='last_update',
            new_name='between_last_updates',
        ),
    ]
