# Generated by Django 4.1.7 on 2023-03-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_between_last_updates_betweenallupdates_between_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='last_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
