# Generated by Django 4.1.7 on 2023-03-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_quiz_last_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='updated',
            new_name='last_view',
        ),
    ]
